"""add spend category, benefit checks, offer reports

Revision ID: 42233a1cd5b9
Revises: 51391169f0c8
Create Date: 2026-09-08 18:47:42.444192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import String, Text  # noqa: F401  (autogenerate가 참조)
import app.core.types  # noqa: F401  방언 독립 커스텀 타입(GUIDType 등)
import pgvector.sqlalchemy  # noqa: F401  임베딩 컬럼(PG는 vector 타입)


# revision identifiers, used by Alembic.
revision: str = '42233a1cd5b9'
down_revision: Union[str, Sequence[str], None] = '51391169f0c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

#: 지출 분야. app.models.store.SpendCategory 와 같아야 한다.
_SPEND_CATEGORY = ("FOOD", "TRANSPORT", "CULTURE", "STUDY", "LIVING", "FIXED", "FINANCE")


def _spend_category(bind) -> sa.types.TypeEngine:
    """컬럼에 붙일 타입.

    PostgreSQL 은 ENUM 타입을 **먼저 만들어** 두어야 컬럼을 추가할 수 있다.
    create_table 은 Alembic 이 타입을 자동 생성해 주지만 add_column 은 해 주지
    않아서, 이 마이그레이션이 빈 PostgreSQL 에서 실패했다. 타입을 직접 만들고
    컬럼 쪽은 create_type=False 로 다시 만들지 않게 한다.
    """
    if bind.dialect.name != "postgresql":
        return sa.Enum(*_SPEND_CATEGORY, name="spend_category")

    from sqlalchemy.dialects import postgresql

    sa.Enum(*_SPEND_CATEGORY, name="spend_category").create(bind, checkfirst=True)
    return postgresql.ENUM(*_SPEND_CATEGORY, name="spend_category", create_type=False)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    spend_category = _spend_category(op.get_bind())
    op.create_table('user_benefit_checks',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', app.core.types.GUIDType(length=36), nullable=False),
    sa.Column('item_key', sa.String(length=60), nullable=False),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_key', name='uq_benefit_check_user_item')
    )
    with op.batch_alter_table('user_benefit_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_benefit_checks_item_key'), ['item_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_benefit_checks_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', spend_category, nullable=True))
        batch_op.create_index(batch_op.f('ix_posts_category'), ['category'], unique=False)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_offer_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True))
        batch_op.create_unique_constraint('uq_report_offer', ['store_offer_id', 'reporter_id'])
        batch_op.create_foreign_key(
            'fk_report_store_offer', 'store_offers', ['store_offer_id'], ['id'],
            ondelete='CASCADE',
        )

    with op.batch_alter_table('saving_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', spend_category, nullable=True))
        batch_op.create_index(batch_op.f('ix_saving_records_category'), ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saving_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saving_records_category'))
        batch_op.drop_column('category')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint('fk_report_store_offer', type_='foreignkey')
        batch_op.drop_constraint('uq_report_offer', type_='unique')
        batch_op.drop_column('store_offer_id')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_category'))
        batch_op.drop_column('category')

    with op.batch_alter_table('user_benefit_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_benefit_checks_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_benefit_checks_item_key'))

    op.drop_table('user_benefit_checks')

    # 컬럼을 지운 뒤에야 타입을 지울 수 있다. upgrade 에서 직접 만들었으므로
    # 여기서도 직접 지운다(Alembic 이 자동으로 해 주지 않는다).
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        sa.Enum(name="spend_category").drop(bind, checkfirst=True)
    # ### end Alembic commands ###
