"""add spend category, benefit checks, offer reports

Revision ID: 42233a1cd5b9
Revises: 51391169f0c8
Create Date: 2026-09-08 18:47:42.444192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import String, Text  # noqa: F401  (autogenerate가 참조)
import app.core.types  # noqa: F401  방언 독립 커스텀 타입(GUIDType 등)
import pgvector.sqlalchemy  # noqa: F401  임베딩 컬럼(PG는 vector 타입)


# revision identifiers, used by Alembic.
revision: str = '42233a1cd5b9'
down_revision: Union[str, Sequence[str], None] = '51391169f0c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_benefit_checks',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', app.core.types.GUIDType(length=36), nullable=False),
    sa.Column('item_key', sa.String(length=60), nullable=False),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_key', name='uq_benefit_check_user_item')
    )
    with op.batch_alter_table('user_benefit_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_benefit_checks_item_key'), ['item_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_benefit_checks_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Enum('FOOD', 'TRANSPORT', 'CULTURE', 'STUDY', 'LIVING', 'FIXED', 'FINANCE', name='spend_category'), nullable=True))
        batch_op.create_index(batch_op.f('ix_posts_category'), ['category'], unique=False)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_offer_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True))
        batch_op.create_unique_constraint('uq_report_offer', ['store_offer_id', 'reporter_id'])
        batch_op.create_foreign_key(
            'fk_report_store_offer', 'store_offers', ['store_offer_id'], ['id'],
            ondelete='CASCADE',
        )

    with op.batch_alter_table('saving_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Enum('FOOD', 'TRANSPORT', 'CULTURE', 'STUDY', 'LIVING', 'FIXED', 'FINANCE', name='spend_category'), nullable=True))
        batch_op.create_index(batch_op.f('ix_saving_records_category'), ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saving_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saving_records_category'))
        batch_op.drop_column('category')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint('fk_report_store_offer', type_='foreignkey')
        batch_op.drop_constraint('uq_report_offer', type_='unique')
        batch_op.drop_column('store_offer_id')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_category'))
        batch_op.drop_column('category')

    with op.batch_alter_table('user_benefit_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_benefit_checks_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_benefit_checks_item_key'))

    op.drop_table('user_benefit_checks')
    # ### end Alembic commands ###
