"""initial schema

Revision ID: 55aebbb81c21
Revises: 
Create Date: 2026-09-01 16:10:10.225458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import String, Text
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy  # 임베딩 컬럼(PG에서 vector 타입)
import app.core.types  # 방언 독립 커스텀 타입(GUIDType 등)

# revision identifiers, used by Alembic.
revision: str = '55aebbb81c21'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('card_key', sa.String(length=100), nullable=False),
    sa.Column('card_name', sa.String(length=200), nullable=False),
    sa.Column('issuer', sa.String(length=100), nullable=True),
    sa.Column('issuance_status', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cards_card_key'), ['card_key'], unique=True)

    op.create_table('crawl_runs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_months', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('total_fetched', sa.Integer(), nullable=False),
    sa.Column('total_saved', sa.Integer(), nullable=False),
    sa.Column('total_expired', sa.Integer(), nullable=False),
    sa.Column('per_platform', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED', name='crawl_run_status'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('local_benefit_merchants',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('source_key', sa.String(length=100), nullable=False),
    sa.Column('merchant_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('CONVENIENCE', 'CAFE', 'RESTAURANT', 'MART', 'BAKERY', 'HNB', 'OTHER', name='local_benefit_store_category'), nullable=False),
    sa.Column('category_label', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('search_query', sa.String(length=700), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('programs', sa.JSON(), nullable=False),
    sa.Column('credentials', sa.JSON(), nullable=False),
    sa.Column('requires', sa.String(length=500), nullable=True),
    sa.Column('benefit_text', sa.Text(), nullable=False),
    sa.Column('discount_type', sa.String(length=30), nullable=True),
    sa.Column('discount_value', sa.Float(), nullable=True),
    sa.Column('min_spend', sa.Float(), nullable=True),
    sa.Column('max_amount', sa.Float(), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('local_benefit_merchants', schema=None) as batch_op:
        batch_op.create_index('ix_local_benefit_category_active', ['category', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_local_benefit_merchants_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_local_benefit_merchants_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_local_benefit_merchants_merchant_name'), ['merchant_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_local_benefit_merchants_source_key'), ['source_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_local_benefit_merchants_source_type'), ['source_type'], unique=False)

    op.create_table('scholarships',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('content_key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('organization', sa.String(length=300), nullable=True),
    sa.Column('source_type', sa.Enum('PUBLIC', 'PRIVATE', name='source_type'), nullable=False),
    sa.Column('category', sa.Enum('SCHOLARSHIP', 'GOV_BENEFIT', name='category'), nullable=False),
    sa.Column('source_platform', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recruit_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eligibility', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('benefit', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('required_documents', sa.JSON().with_variant(postgresql.ARRAY(String()), 'postgresql'), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSING_SOON', 'CLOSED', 'SCHEDULE_CHANGED', 'NEEDS_REVIEW', name='posting_status'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('crawled_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scholarships', schema=None) as batch_op:
        batch_op.create_index('ix_scholarships_cat_deadline', ['category', 'deadline_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scholarships_content_key'), ['content_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_scholarships_deadline_at'), ['deadline_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scholarships_posted_at'), ['posted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scholarships_source_platform'), ['source_platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_scholarships_status'), ['status'], unique=False)

    op.create_table('stores',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('branch', sa.String(length=150), nullable=False),
    sa.Column('category', sa.Enum('CONVENIENCE', 'CAFE', 'RESTAURANT', 'MART', 'BAKERY', 'HNB', 'OTHER', name='store_category'), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('mark', sa.String(length=10), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'branch', name='uq_store_brand_branch')
    )
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stores_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_stores_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_stores_lat'), ['lat'], unique=False)
        batch_op.create_index('ix_stores_lat_lng', ['lat', 'lng'], unique=False)
        batch_op.create_index(batch_op.f('ix_stores_lng'), ['lng'], unique=False)

    op.create_table('users',
    sa.Column('id', app.core.types.GUIDType(length=36), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('income_bracket', sa.Integer(), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('grade_level', sa.String(length=10), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('major', sa.String(length=100), nullable=True),
    sa.Column('interests', sa.JSON().with_variant(postgresql.ARRAY(String()), 'postgresql'), nullable=False),
    sa.Column('preferred_pay_methods', sa.JSON().with_variant(postgresql.ARRAY(String()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('card_benefits',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('card_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('dedup_key', sa.String(length=64), nullable=False),
    sa.Column('merchant_raw', sa.String(length=200), nullable=False),
    sa.Column('brand_key', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('benefit_type', sa.Enum('PERCENT', 'AMOUNT', 'CASHBACK', 'EVENT', 'UNVERIFIED', 'EXPIRED', name='benefit_type'), nullable=False),
    sa.Column('value_min', sa.Float(), nullable=True),
    sa.Column('value_max', sa.Float(), nullable=True),
    sa.Column('benefit_text', sa.String(length=300), nullable=True),
    sa.Column('min_payment_krw', sa.Integer(), nullable=True),
    sa.Column('min_payment_raw', sa.String(length=100), nullable=True),
    sa.Column('cap_text', sa.String(length=200), nullable=True),
    sa.Column('period_type', sa.Enum('ALWAYS_ON', 'MONTHLY', 'WEEK4', name='period_type'), nullable=True),
    sa.Column('period_text', sa.String(length=120), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('conditions', sa.JSON().with_variant(postgresql.ARRAY(String()), 'postgresql'), nullable=False),
    sa.Column('excludes_simple_pay', sa.Boolean(), nullable=False),
    sa.Column('stackable_note', sa.String(length=200), nullable=True),
    sa.Column('confidence', sa.Enum('CONFIRMED', 'CONDITIONAL', 'UNVERIFIED', name='benefit_confidence'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_as_of', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card_benefits', schema=None) as batch_op:
        batch_op.create_index('ix_card_benefits_brand_active', ['brand_key', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_benefits_brand_key'), ['brand_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_benefits_card_id'), ['card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_benefits_dedup_key'), ['dedup_key'], unique=True)

    op.create_table('scholarship_embeddings',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('scholarship_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('chunk_type', sa.String(length=30), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON().with_variant(pgvector.sqlalchemy.vector.VECTOR(dim=256), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scholarship_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scholarship_embeddings_scholarship_id'), ['scholarship_id'], unique=False)

    op.create_table('store_offers',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('pay_method', sa.Enum('KAKAO', 'TOSS', 'NAVER', name='pay_method'), nullable=False),
    sa.Column('discount_rate', sa.Integer(), nullable=False),
    sa.Column('condition_text', sa.String(length=300), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'pay_method', name='uq_offer_store_paymethod')
    )
    with op.batch_alter_table('store_offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_offers_pay_method'), ['pay_method'], unique=False)
        batch_op.create_index(batch_op.f('ix_store_offers_store_id'), ['store_id'], unique=False)

    op.create_table('user_applications',
    sa.Column('id', app.core.types.GUIDType(length=36), nullable=False),
    sa.Column('user_id', app.core.types.GUIDType(length=36), nullable=False),
    sa.Column('scholarship_name', sa.String(length=500), nullable=False),
    sa.Column('organization', sa.String(length=300), nullable=True),
    sa.Column('scholarship_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('source', sa.Enum('UPLOADED', 'GENERATED', name='application_source'), nullable=False),
    sa.Column('result', sa.Enum('DRAFT', 'SUBMITTED', 'ACCEPTED', 'REJECTED', name='application_result'), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.ARRAY(String()), 'postgresql'), nullable=False),
    sa.Column('is_reusable', sa.Boolean(), nullable=False),
    sa.Column('source_file_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarships.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_applications_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_applications_user_id'), ['user_id'], unique=False)

    op.create_table('application_documents',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('application_id', app.core.types.GUIDType(length=36), nullable=False),
    sa.Column('doc_type', sa.Enum('SELF_INTRO', 'STUDY_PLAN', 'ACTIVITY', 'OTHER', name='doc_type'), nullable=False),
    sa.Column('prompt_question', sa.Text(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('embedding_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['user_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_documents_application_id'), ['application_id'], unique=False)

    op.create_table('document_embeddings',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON().with_variant(pgvector.sqlalchemy.vector.VECTOR(dim=256), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['application_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_embeddings_document_id'), ['document_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_embeddings_document_id'))

    op.drop_table('document_embeddings')
    with op.batch_alter_table('application_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_documents_application_id'))

    op.drop_table('application_documents')
    with op.batch_alter_table('user_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_applications_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_applications_source'))

    op.drop_table('user_applications')
    with op.batch_alter_table('store_offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_offers_store_id'))
        batch_op.drop_index(batch_op.f('ix_store_offers_pay_method'))

    op.drop_table('store_offers')
    with op.batch_alter_table('scholarship_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scholarship_embeddings_scholarship_id'))

    op.drop_table('scholarship_embeddings')
    with op.batch_alter_table('card_benefits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_benefits_dedup_key'))
        batch_op.drop_index(batch_op.f('ix_card_benefits_card_id'))
        batch_op.drop_index(batch_op.f('ix_card_benefits_brand_key'))
        batch_op.drop_index('ix_card_benefits_brand_active')

    op.drop_table('card_benefits')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stores_lng'))
        batch_op.drop_index('ix_stores_lat_lng')
        batch_op.drop_index(batch_op.f('ix_stores_lat'))
        batch_op.drop_index(batch_op.f('ix_stores_category'))
        batch_op.drop_index(batch_op.f('ix_stores_brand'))

    op.drop_table('stores')
    with op.batch_alter_table('scholarships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scholarships_status'))
        batch_op.drop_index(batch_op.f('ix_scholarships_source_platform'))
        batch_op.drop_index(batch_op.f('ix_scholarships_posted_at'))
        batch_op.drop_index(batch_op.f('ix_scholarships_deadline_at'))
        batch_op.drop_index(batch_op.f('ix_scholarships_content_key'))
        batch_op.drop_index('ix_scholarships_cat_deadline')

    op.drop_table('scholarships')
    with op.batch_alter_table('local_benefit_merchants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_local_benefit_merchants_source_type'))
        batch_op.drop_index(batch_op.f('ix_local_benefit_merchants_source_key'))
        batch_op.drop_index(batch_op.f('ix_local_benefit_merchants_merchant_name'))
        batch_op.drop_index(batch_op.f('ix_local_benefit_merchants_is_active'))
        batch_op.drop_index(batch_op.f('ix_local_benefit_merchants_category'))
        batch_op.drop_index('ix_local_benefit_category_active')

    op.drop_table('local_benefit_merchants')
    op.drop_table('crawl_runs')
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cards_card_key'))

    op.drop_table('cards')
    # ### end Alembic commands ###
