"""add user onboarding profile fields

Revision ID: 943634768edf
Revises: fbdfd96f8275
Create Date: 2026-09-01 17:19:58.245987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import String, Text  # noqa: F401  (autogenerate가 참조)
import app.core.types  # noqa: F401  방언 독립 커스텀 타입(GUIDType 등)
import pgvector.sqlalchemy  # noqa: F401  임베딩 컬럼(PG는 vector 타입)
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '943634768edf'
down_revision: Union[str, Sequence[str], None] = 'fbdfd96f8275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('telecom', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('card_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False))
        batch_op.add_column(sa.Column('student_credentials', sa.JSON().with_variant(postgresql.ARRAY(String()), 'postgresql'), nullable=False))
        batch_op.add_column(sa.Column('benefit_programs', sa.JSON().with_variant(postgresql.ARRAY(String()), 'postgresql'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('benefit_programs')
        batch_op.drop_column('student_credentials')
        batch_op.drop_column('card_ids')
        batch_op.drop_column('telecom')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
