"""add email verification reminder consent

Revision ID: d2aaf04ab078
Revises: dcf2e77c8733
Create Date: 2026-09-28 23:39:40.158590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import String, Text  # noqa: F401  (autogenerate가 참조)
import app.core.types  # noqa: F401  방언 독립 커스텀 타입(GUIDType 등)
import pgvector.sqlalchemy  # noqa: F401  임베딩 컬럼(PG는 vector 타입)


# revision identifiers, used by Alembic.
revision: str = 'd2aaf04ab078'
down_revision: Union[str, Sequence[str], None] = 'dcf2e77c8733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('reminder_enabled', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('privacy_consent_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('store_offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_sample', sa.Boolean(), server_default=sa.false(), nullable=False))

    # 지금까지 들어간 간편결제 혜택은 전부 시드가 넣은 예시 값이다.
    op.execute(sa.text('UPDATE store_offers SET is_sample = :t').bindparams(t=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store_offers', schema=None) as batch_op:
        batch_op.drop_column('is_sample')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('privacy_consent_at')
        batch_op.drop_column('reminder_enabled')
        batch_op.drop_column('email_verified_at')

    # ### end Alembic commands ###
