"""add post image_names

Revision ID: dcf2e77c8733
Revises: 42233a1cd5b9
Create Date: 2026-09-22 13:52:41.837661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import String, Text  # noqa: F401  (autogenerate가 참조)
import app.core.types  # noqa: F401  방언 독립 커스텀 타입(GUIDType 등)
import pgvector.sqlalchemy  # noqa: F401  임베딩 컬럼(PG는 vector 타입)
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dcf2e77c8733'
down_revision: Union[str, Sequence[str], None] = '42233a1cd5b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_names', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False, server_default='[]'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('image_names')

    # ### end Alembic commands ###
