"""add saving_records

Revision ID: e7d84e04b746
Revises: 55aebbb81c21
Create Date: 2026-09-01 16:20:34.569325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import String, Text  # noqa: F401
import app.core.types  # noqa: F401
import pgvector.sqlalchemy  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'e7d84e04b746'
down_revision: Union[str, Sequence[str], None] = '55aebbb81c21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saving_records',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', app.core.types.GUIDType(length=36), nullable=False),
    sa.Column('kind', sa.Enum('VIEWED', 'SPENT', name='saving_kind'), nullable=False),
    sa.Column('store_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('store_label', sa.String(length=200), nullable=False),
    sa.Column('original_amount', sa.Float(), nullable=False),
    sa.Column('final_amount', sa.Float(), nullable=False),
    sa.Column('saved_amount', sa.Float(), nullable=False),
    sa.Column('method_label', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saving_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saving_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_saving_records_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_saving_records_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saving_records_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_saving_user_created', ['user_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saving_records', schema=None) as batch_op:
        batch_op.drop_index('ix_saving_user_created')
        batch_op.drop_index(batch_op.f('ix_saving_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_saving_records_store_id'))
        batch_op.drop_index(batch_op.f('ix_saving_records_kind'))
        batch_op.drop_index(batch_op.f('ix_saving_records_created_at'))

    op.drop_table('saving_records')
    # ### end Alembic commands ###
